version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    environment:
      - DATABASE_HOST=postgres_db
      - DATABASE_USER=admin
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=mydb
    depends_on:
      - postgres_db
  postgres_db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydb
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
