trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  terraformVersion: '1.4.0'

steps:
- task: UseTerraform@0
  inputs:
    terraformVersion: $(terraformVersion)

- script: |
    terraform init
    terraform plan -out=tfplan
    terraform apply -auto-approve tfplan
  displayName: 'Run Terraform'
